{
 "title": "Cooja Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Sensor Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "cooja",
     "rawSql": "SELECT alive, sensor_name FROM cooja.sensor_status LIMIT 50 "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "cooja",
     "rawSql": "SELECT sensor_name, timestamp, value FROM cooja.sensor_values\nJOIN sensors ON sensors.id = sensor_values.sensor_id\nWHERE sensor_type_id = 2;\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "cooja",
     "rawSql": "SELECT sensor_name, timestamp, value FROM cooja.sensor_values\nJOIN sensors ON sensors.id = sensor_values.sensor_id\nWHERE sensor_type_id = 1;\n"
    }
   ]
  },
  {
   "title": "Attack Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cooja",
     "rawSql": "SELECT \n    'Attack' AS \"category\", \n    COUNT(*) AS \"value\" \nFROM packets \nWHERE is_attack = 1\nUNION ALL\nSELECT \n    'Not Attack' AS \"category\", \n    COUNT(*) AS \"value\" \nFROM packets \nWHERE is_attack = 0;\n"
    }
   ]
  }
 ]
}